### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [hdgarrood/hdgarrood.github.io#1]
Hi! I am the editor of Haskell Weekly. I would like to be notified when you publish a new post, but as far as I can tell your site does not have a feed. Would you mind adding an Atom or RSS feed? Thanks!

**Comment by hdgarrood** [comment]
Done, thanks for the reminder!

**Comment by tfausak** [comment]
🎉 Great, thanks! I was able to use the feed at <https://harry.garrood.me/atom.xml>.
